export { BarcodeScanner } from './BarcodeScanner'
export { Html5QrcodeScannerService } from './services/Html5QrcodeScannerService'
export type { IScannerService, IScanResult, IScannerError } from './interfaces/IScannerService'
export { useScannerState } from './hooks/useScannerState'
export type { ScanStatus, ScannerState } from './hooks/useScannerState'