export { BarcodeScanner } from './BarcodeScanner'
export { default as BarcodeScannerDefault } from './BarcodeScanner'
export { ReactQrBarcodeScannerService } from './services/ReactQrBarcodeScannerService'
export type { IScannerService, IScanResult, IScannerError } from './interfaces/IScannerService'
export { useScannerState } from './hooks/useScannerState'
export type { ScanStatus, ScannerState } from './hooks/useScannerState' 